# See CODEOWNERS for the source of truth.

policy:
  - section:
      - id: [command]
        label:
          - name: software-delivery
            keys:
              - coverage
              - deployment
              - dora
              - junit
              - metric
              - tag
              - trace
          - name: static-analysis
            keys:
              - sarif
              - sbom
          - name: profiling
            keys:
              - elf-symbols
          - name: rum
            keys:
              - dsyms
              - flutter-symbols
              - react-native
              - sourcemaps
              - unity-symbols
          - name: serverless
            keys:
              - cloud-run
              - lambda
              - stepfunctions
          - name: source-code-integration
            keys:
              - git-metadata
              - gate
          - name: synthetics
            keys:
              - synthetics
          - name: profiling
            keys:
              - elf-symbols
