stages:
  - build
  - release

variables:
  INTERNAL_REGISTRY: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci

build-docker-image-amd64:
  stage: build
  tags: ["runner:docker"]
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/docker:20.10
  script:
    - cd container
    - docker build --build-arg "VERSION=" --tag "${INTERNAL_REGISTRY}/datadog-ci:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-amd64" .
    - docker push "${INTERNAL_REGISTRY}/datadog-ci:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-amd64"

build-docker-image-arm64:
  stage: build
  tags: ["runner:docker-arm", "platform:arm64"]
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/docker:20.10
  script:
    - cd container
    - docker build --build-arg "VERSION=" --tag "${INTERNAL_REGISTRY}/datadog-ci:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-arm64" .
    - docker push "${INTERNAL_REGISTRY}/datadog-ci:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-arm64"

publish-docker-image:
  stage: release
  trigger:
    project: DataDog/public-images
    branch: main
    strategy: depend
  variables:
    IMG_SOURCES: ${INTERNAL_REGISTRY}/datadog-ci:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-amd64,${INTERNAL_REGISTRY}/datadog-ci:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}-arm64
    IMG_DESTINATIONS: ci:latest
    IMG_SIGNING: "false"
