name: Remove me

on: push

jobs:
  bump-ci-integrations:
    name: Bump datadog-ci in integration
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        integration-repo:
          - synthetics-ci-github-action
          - datadog-ci-azure-devops
          - synthetics-test-automation-circleci-orb
          - synthetics-test-automation-bitrise-step-run-tests
          - synthetics-test-automation-bitrise-step-upload-application
          - synthetics-batch-smoke-tester
    steps:
      - name: Get GitHub App token
        id: get-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.RELEASE_AUTOMATION_GITHUB_APP_ID }}
          private-key: ${{ secrets.RELEASE_AUTOMATION_GITHUB_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: ${{ matrix.integration-repo }}
      - name: Create bump datadog-ci PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.get-token.outputs.token }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: '${{ matrix.integration-repo }}',
              workflow_id: 'bump-datadog-ci.yml',
              ref: 'main',
              inputs: {
                datadog_ci_version: 'unknown',
              },
            })
